### ISSUE TITLE
Socket closed

### ISSUE THREAD

**Issue by h1rule** [cybertim/iagobot#3]
BinTreeNodeReader:      Incoming
ReaderThread:   Socket closed, got 0 bytes!
ReaderThread:   Sending disconnected because of closed
YowsupConnectionManager:        Setting state to 0

Does it fix itself or do i have to restart the bot?

**Comment by cybertim** [comment]
You can better ask the yowsup git ..
But in my experience, you need to restart the bot (and thus yowsup).
